name: Rails CI

on:
  push:

jobs:
  test:
    name: Run Tests and Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --without development

      - name: Run RSpec tests
        run: bundle exec rspec
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432/simple_mailer_test

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./spec/reports # Adjust the path based on your configuration