name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.3

    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3

    - name: Run tests
      run: bundle exec rails test
      
